# Generates a C++ translation unit containing the compiled SPIR-V corpus, so
# the library can create its shader modules with no filesystem access at all.
# See library/include/vkapriltag/vk/EmbeddedShaders.h for why that matters.
#
# Run via `cmake -P`, not included:
#
#   cmake -DSPV_FILES="a.spv|b.spv" -DOUTPUT=embedded_shaders.cpp -DEMBED=ON
#         -P GenerateEmbeddedShaders.cmake
#
# With EMBED=OFF it still runs and still writes OUTPUT, but emits an empty
# table. That keeps the build graph and the call sites identical either way -
# the disk fallback is selected at runtime by HasEmbeddedShaders(), not by a
# preprocessor branch threaded through GpuDetector.

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "GenerateEmbeddedShaders: OUTPUT not set")
endif()

if(NOT DEFINED EMBED)
  set(EMBED ON)
endif()

# The file list arrives '|'-separated: a ';'-separated list passed through -D
# would be split into separate command-line arguments before it ever reached
# this script.
if(DEFINED SPV_FILES)
  string(REPLACE "|" ";" SPV_FILES "${SPV_FILES}")
endif()

# Sort by path so the emitted order - and therefore the corpus digest - does
# not depend on the order CMake happened to hand us the file list in.
set(SPV_SORTED "")
if(DEFINED SPV_FILES AND EMBED)
  set(SPV_SORTED ${SPV_FILES})
  list(SORT SPV_SORTED)
endif()

set(ARRAYS "")
set(TABLE "")
set(DIGEST_INPUT "")

# Matches exactly kBytesPerLine consecutive "0xNN," groups, for line wrapping
# below. Spelled out rather than written "(0x..,){16}" because CMake's regex
# engine has no {n} repetition operator - it accepts the syntax as literal
# characters and silently matches nothing.
set(BYTES_PER_LINE 16)
set(LINE_PATTERN "")
foreach(UNUSED RANGE 1 ${BYTES_PER_LINE})
  string(APPEND LINE_PATTERN "0x..,")
endforeach()

foreach(SPV_PATH ${SPV_SORTED})
  if(NOT EXISTS "${SPV_PATH}")
    message(FATAL_ERROR "GenerateEmbeddedShaders: missing SPIR-V file ${SPV_PATH}")
  endif()

  # "decimate.comp.spv" -> "decimate"; that is the name GpuDetector asks for.
  get_filename_component(SPV_NAME "${SPV_PATH}" NAME)
  string(REGEX REPLACE "\\.comp\\.spv$" "" SHADER_NAME "${SPV_NAME}")
  string(REGEX REPLACE "\\.spv$" "" SHADER_NAME "${SHADER_NAME}")
  string(MAKE_C_IDENTIFIER "${SHADER_NAME}" SYMBOL)

  file(READ "${SPV_PATH}" SPV_HEX HEX)
  string(LENGTH "${SPV_HEX}" HEX_LEN)
  math(EXPR BYTE_COUNT "${HEX_LEN} / 2")
  math(EXPR REMAINDER "${BYTE_COUNT} % 4")
  if(NOT REMAINDER EQUAL 0)
    message(FATAL_ERROR
      "GenerateEmbeddedShaders: ${SPV_PATH} is ${BYTE_COUNT} bytes, not a multiple of 4 - "
      "that is not valid SPIR-V")
  endif()

  # Each file's own digest feeds the corpus digest below. Hashing the digests
  # rather than the bytes keeps this cheap: the corpus is ~half a megabyte,
  # and CMake string ops over that much hex are not free.
  file(MD5 "${SPV_PATH}" SPV_MD5)
  string(APPEND DIGEST_INPUT "${SHADER_NAME}:${SPV_MD5};")

  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," SPV_BYTES "${SPV_HEX}")
  # Wrap at BYTES_PER_LINE per line. A single multi-hundred-kilobyte source
  # line is legal C++ but not every compiler is happy about it.
  string(REGEX REPLACE "(${LINE_PATTERN})" "\\1\n    " SPV_BYTES "${SPV_BYTES}")

  # alignas(4) is load-bearing: VkShaderModuleCreateInfo::pCode is a
  # const uint32_t*, and the cast below is only defined if the storage is
  # actually 4-byte aligned. A bare unsigned char array carries no such
  # guarantee.
  string(APPEND ARRAYS
    "alignas(4) const unsigned char k_${SYMBOL}[] = {\n    ${SPV_BYTES}\n};\n\n")
  string(APPEND TABLE
    "    {\"${SHADER_NAME}\", reinterpret_cast<const uint32_t *>(k_${SYMBOL}), ${BYTE_COUNT}u},\n")
endforeach()

list(LENGTH SPV_SORTED SHADER_COUNT)

if(SHADER_COUNT EQUAL 0)
  set(CORPUS_HASH "0ull")
else()
  string(MD5 DIGEST "${DIGEST_INPUT}")
  string(SUBSTRING "${DIGEST}" 0 16 DIGEST64)
  set(CORPUS_HASH "0x${DIGEST64}ull")
endif()

set(GENERATED "\
// Generated by cmake/GenerateEmbeddedShaders.cmake. Do not edit.
//
// Shaders embedded: ${SHADER_COUNT}

#include \"vkapriltag/vk/EmbeddedShaders.h\"

#include <cstring>

namespace apriltag_vulkan::vk {
namespace {

${ARRAYS}\
const EmbeddedShader kShaders[] = {
${TABLE}\
};

constexpr size_t kShaderCount = ${SHADER_COUNT};

}  // namespace

const EmbeddedShader *FindEmbeddedShader(const char *name) {
  if (name == nullptr) return nullptr;
  for (size_t i = 0; i < kShaderCount; ++i) {
    if (std::strcmp(kShaders[i].name, name) == 0) return &kShaders[i];
  }
  return nullptr;
}

bool HasEmbeddedShaders() { return kShaderCount > 0; }

uint64_t EmbeddedShaderCorpusHash() { return ${CORPUS_HASH}; }

}  // namespace apriltag_vulkan::vk
")

# An empty corpus emits `const EmbeddedShader kShaders[] = {};`, which is a
# zero-length array - ill-formed in standard C++ even though every compiler
# accepts it as an extension. Emit a single inert entry instead and keep
# kShaderCount at 0, so the loop above never reads it.
if(SHADER_COUNT EQUAL 0)
  string(REPLACE "const EmbeddedShader kShaders[] = {\n};"
                 "const EmbeddedShader kShaders[] = {\n    {\"\", nullptr, 0u},\n};"
                 GENERATED "${GENERATED}")
endif()

# Written unconditionally, on purpose. The build system decides whether to run
# this script at all by comparing OUTPUT's timestamp against the .spv files;
# skipping the write when the contents match would leave OUTPUT older than its
# inputs and re-run the generator on every single build.
file(WRITE "${OUTPUT}" "${GENERATED}")
