# Generates a C++ translation unit embedding the compiled SPIR-V corpus (see vk/EmbeddedShaders.h).
#
# Run via `cmake -P`, not included:
#
#   cmake -DSPV_FILES="a.spv|b.spv" -DOUTPUT=embedded_shaders.cpp -DEMBED=ON
#         -P GenerateEmbeddedShaders.cmake
#
# With EMBED=OFF it writes an empty table; the disk fallback is chosen at runtime by HasEmbeddedShaders().

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "GenerateEmbeddedShaders: OUTPUT not set")
endif()

if(NOT DEFINED EMBED)
  set(EMBED ON)
endif()

# '|'-separated because -D would split a ';'-separated list.
if(DEFINED SPV_FILES)
  string(REPLACE "|" ";" SPV_FILES "${SPV_FILES}")
endif()

# Sorted by path so the emitted order and corpus digest are deterministic.
set(SPV_SORTED "")
if(DEFINED SPV_FILES AND EMBED)
  set(SPV_SORTED ${SPV_FILES})
  list(SORT SPV_SORTED)
endif()

set(ARRAYS "")
set(TABLE "")
set(DIGEST_INPUT "")

# Matches kBytesPerLine consecutive "0xNN," groups (CMake regex has no {n} repetition).
set(BYTES_PER_LINE 16)
set(LINE_PATTERN "")
foreach(UNUSED RANGE 1 ${BYTES_PER_LINE})
  string(APPEND LINE_PATTERN "0x..,")
endforeach()

foreach(SPV_PATH ${SPV_SORTED})
  if(NOT EXISTS "${SPV_PATH}")
    message(FATAL_ERROR "GenerateEmbeddedShaders: missing SPIR-V file ${SPV_PATH}")
  endif()

  # "decimate.comp.spv" -> "decimate", the name GpuDetector requests.
  get_filename_component(SPV_NAME "${SPV_PATH}" NAME)
  string(REGEX REPLACE "\\.comp\\.spv$" "" SHADER_NAME "${SPV_NAME}")
  string(REGEX REPLACE "\\.spv$" "" SHADER_NAME "${SHADER_NAME}")
  string(MAKE_C_IDENTIFIER "${SHADER_NAME}" SYMBOL)

  file(READ "${SPV_PATH}" SPV_HEX HEX)
  string(LENGTH "${SPV_HEX}" HEX_LEN)
  math(EXPR BYTE_COUNT "${HEX_LEN} / 2")
  math(EXPR REMAINDER "${BYTE_COUNT} % 4")
  if(NOT REMAINDER EQUAL 0)
    message(FATAL_ERROR
      "GenerateEmbeddedShaders: ${SPV_PATH} is ${BYTE_COUNT} bytes, not a multiple of 4 - "
      "that is not valid SPIR-V")
  endif()

  # Each file's digest feeds the corpus digest.
  file(MD5 "${SPV_PATH}" SPV_MD5)
  string(APPEND DIGEST_INPUT "${SHADER_NAME}:${SPV_MD5};")

  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," SPV_BYTES "${SPV_HEX}")
  # Wrap lines at BYTES_PER_LINE bytes.
  string(REGEX REPLACE "(${LINE_PATTERN})" "\\1\n    " SPV_BYTES "${SPV_BYTES}")

  # alignas(4): pCode is read as const uint32_t*.
  string(APPEND ARRAYS
    "alignas(4) const unsigned char k_${SYMBOL}[] = {\n    ${SPV_BYTES}\n};\n\n")
  string(APPEND TABLE
    "    {\"${SHADER_NAME}\", reinterpret_cast<const uint32_t *>(k_${SYMBOL}), ${BYTE_COUNT}u},\n")
endforeach()

list(LENGTH SPV_SORTED SHADER_COUNT)

if(SHADER_COUNT EQUAL 0)
  set(CORPUS_HASH "0ull")
else()
  string(MD5 DIGEST "${DIGEST_INPUT}")
  string(SUBSTRING "${DIGEST}" 0 16 DIGEST64)
  set(CORPUS_HASH "0x${DIGEST64}ull")
endif()

set(GENERATED "\
// Generated by cmake/GenerateEmbeddedShaders.cmake. Do not edit.
//
// Shaders embedded: ${SHADER_COUNT}

#include \"vkapriltag/vk/EmbeddedShaders.h\"

#include <cstring>

namespace apriltag_vulkan::vk {
namespace {

${ARRAYS}\
const EmbeddedShader kShaders[] = {
${TABLE}\
};

constexpr size_t kShaderCount = ${SHADER_COUNT};

}  // namespace

const EmbeddedShader *FindEmbeddedShader(const char *name) {
  if (name == nullptr) return nullptr;
  for (size_t i = 0; i < kShaderCount; ++i) {
    if (std::strcmp(kShaders[i].name, name) == 0) return &kShaders[i];
  }
  return nullptr;
}

bool HasEmbeddedShaders() { return kShaderCount > 0; }

uint64_t EmbeddedShaderCorpusHash() { return ${CORPUS_HASH}; }

}  // namespace apriltag_vulkan::vk
")

# Empty corpus: emit one inert entry (zero-length arrays are ill-formed) and keep kShaderCount at 0.
if(SHADER_COUNT EQUAL 0)
  string(REPLACE "const EmbeddedShader kShaders[] = {\n};"
                 "const EmbeddedShader kShaders[] = {\n    {\"\", nullptr, 0u},\n};"
                 GENERATED "${GENERATED}")
endif()

# Written unconditionally so OUTPUT stays newer than the .spv inputs.
file(WRITE "${OUTPUT}" "${GENERATED}")
