#pragma once

// Embedded SPIR-V shaders
// These would normally be generated by compiling the .comp files to SPIR-V

#include <stddef.h>
#include <stdint.h>

// Placeholder SPIR-V data - in a real implementation, these would be
// generated by compiling the shader source files with glslangValidator or similar

// Threshold shader SPIR-V
extern const uint32_t threshold_comp_spirv[];
extern const size_t threshold_comp_spirv_size;

// Connected components shader SPIR-V
extern const uint32_t connected_components_comp_spirv[];
extern const size_t connected_components_comp_spirv_size;

// Gradient shader SPIR-V
extern const uint32_t gradient_comp_spirv[];
extern const size_t gradient_comp_spirv_size;

// Decimation shader SPIR-V
extern const uint32_t decimate_comp_spirv[];
extern const size_t decimate_comp_spirv_size;

// Blur shader SPIR-V
extern const uint32_t blur_comp_spirv[];
extern const size_t blur_comp_spirv_size;