#include "shaders_spirv.h"

// Note: In a real implementation, these arrays would contain the actual SPIR-V bytecode
// generated by compiling the .comp shader files. For now, these are placeholders.

// Minimal valid SPIR-V header for each shader
// Real implementation would use: glslangValidator -V shader.comp -o shader.spv

const uint32_t threshold_comp_spirv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000001, 0x00000000,
    // ... actual SPIR-V bytecode would go here
};
const size_t threshold_comp_spirv_size = sizeof(threshold_comp_spirv);

const uint32_t connected_components_comp_spirv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000001, 0x00000000,
    // ... actual SPIR-V bytecode would go here
};
const size_t connected_components_comp_spirv_size = sizeof(connected_components_comp_spirv);

const uint32_t gradient_comp_spirv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000001, 0x00000000,
    // ... actual SPIR-V bytecode would go here
};
const size_t gradient_comp_spirv_size = sizeof(gradient_comp_spirv);

const uint32_t decimate_comp_spirv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000001, 0x00000000,
    // ... actual SPIR-V bytecode would go here
};
const size_t decimate_comp_spirv_size = sizeof(decimate_comp_spirv);

const uint32_t blur_comp_spirv[] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000001, 0x00000000,
    // ... actual SPIR-V bytecode would go here
};
const size_t blur_comp_spirv_size = sizeof(blur_comp_spirv);